### ISSUE TITLE
Any plan to provide content in English?

### ISSUE THREAD

**Issue by vinsis** [taichi-dev/games201#3]
Hi, thank you for creating this. The content looks really exciting and I am wondering if any of it will be made available in English sometime in near future. It would be highly appreciated!

**Comment by yuanming-hu** [comment]
Hi @vinsis - thanks for the question. Most slides are already in English: https://github.com/taichi-dev/games201/releases

After the course, I'll release a pure-English compilation of the course slides.

**Comment by vinsis** [comment]
Thank you @yuanming-hu - looking forward to it.
